### ISSUE TITLE
Add autocomplete=off in the input field

### ISSUE THREAD

**Issue by pietercolpaert** [TREEcg/treemunica_typeahead_demo#2]
![Screenshot from 2021-11-05 15-06-32](https://user-images.githubusercontent.com/347073/140523338-b1947996-de10-47bf-a3fd-710f6091503d.png)
↑ This makes sure your default autocomplete in the browser isn’t used

**Comment by Dexagod** [comment]
Fixed in 495925bc10ef23e26ceb82c5939d9b8e3995d96f

**Comment by pietercolpaert** [comment]
@Dexagod This hasn’t been put in production yet at https://tree.linkeddatafragments.org/demo/autocompletion/ - it works on github pages though.
